name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        ubuntu: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.ubuntu }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install cmake python3-catkin-pkg python3-sphinx
      - name: Build test packages
        run: |
          ./test-packages/build-test-packages.sh
